name: pnpm Install
description: Checkout the repository, setup Node.js and install dependencies using pnpm

inputs:
  install-args:
    description: 'Arguments to pass to pnpm install'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: pnpm/action-setup@v3
      with:
        version: 9

    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: pnpm

    - run: pnpm install --frozen-lockfile ${{ inputs.install-args }}
      shell: bash
