name: pnpm Install
description: Checkout the repository, setup Node.js and install dependencies using pnpm

inputs:
  install-args:
    description: 'Arguments to pass to pnpm install'
    required: false
    default: ''
  ref:
    description: 'Git ref to checkout'
    required: false
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Get PNPM version from package.json
      id: pnpm-version
      shell: bash
      run: echo "PNPM_VERSION=$(jq -r '.engines.pnpm' package.json)" >> $GITHUB_OUTPUT

    - uses: pnpm/action-setup@v4
      with:
        version: ${{ steps.pnpm-version.outputs.PNPM_VERSION || '9' }}

    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: pnpm

    - run: pnpm install --frozen-lockfile ${{ inputs.install-args }}
      shell: bash
