name: pnpm Install
description: Checkout the repository, setup Node.js and install dependencies using pnpm

inputs:
  install-args:
    description: 'Arguments to pass to pnpm install'
    required: false
    default: ''
  ref:
    description: 'Git ref to checkout'
    required: false
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    required: false
  registry-url:
    description: 'Optional registry to set up for auth.'
    required: false
  working-directory:
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Get PNPM version from package.json
      id: pnpm-version
      shell: bash
      run: echo "PNPM_VERSION=$(jq -r '.packageManager // .engines.pnpm // ""' package.json)" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.working-directory }}

    - name: Install pnpm with custom version
      uses: pnpm/action-setup@v4
      if: ${{ !startsWith(steps.pnpm-version.outputs.PNPM_VERSION, 'pnpm@') }}
      with:
        version: ${{ steps.pnpm-version.outputs.PNPM_VERSION || '10' }}
        cache_dependency_path: ${{ inputs.working-directory }}/pnpm-lock.yaml
        
    - name: Install pnpm with version from `packageManager`
      uses: pnpm/action-setup@v4
      if: ${{ startsWith(steps.pnpm-version.outputs.PNPM_VERSION, 'pnpm@') }}
      with:
        cache_dependency_path: ${{ inputs.working-directory }}/pnpm-lock.yaml

    - uses: actions/setup-node@v4
      with:
        node-version-file: '${{ inputs.working-directory }}/package.json'
        cache: pnpm
        registry-url: ${{ inputs.registry-url }}

    - run: pnpm install --frozen-lockfile ${{ inputs.install-args }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
